# from: https://github.com/EagerELK/logstash-development-environment/blob/master/provisioning/logstash-dev-rvm.yml
---
- hosts: all
  sudo: true
  vars:
    rvm1_rubies:
      - jruby
    rvm1_install_flags: '--auto-dotfiles --user-install --with-gems="bundler"'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
  pre_tasks:
    - name: Logstash Development | Install dependencies
      yum: "name={{ item }} state=latest"
      with_items:
        - git

    - name: Logstash Development | Get the real JAVA_HOME
      shell: readlink -f `which java` | sed "s/\/bin\/java$//"
      register: java_home
      always_run: true

    - name: Logstash Development | Ensure that the java home is set properly
      lineinfile: >
        dest=/home/vagrant/.bashrc
        line="export JAVA_HOME={{ java_home.stdout }}"
  roles:
    - rvm_io.rvm1-ruby
  tasks:
    - name: Logstash Development | Ensure that the gem home is set properly
      lineinfile: >
        dest=/home/vagrant/.bashrc
        line="export GEM_HOME=$(ruby -e 'puts Gem.user_dir')"
