---

- name: installing dependencies
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - libselinux-python-{{ libselinux_python_version }}
    - epel-release-{{ epel_version }}
    - java-{{ openjdk_version }}-openjdk-devel
    - ant
    - lsof
    - libtool
    - gcc-c++
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel

- name: ntp
  sudo: yes
  yum: name=ntp state=present
  tags: [ntp]

- name: start ntp server
  sudo: yes
  service: name=ntpd state=started enabled=yes
  tags: [ntp]
