---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: install openjdk-devel
  yum: name=java-{{ openjdk_version }}-openjdk-devel state=present

- name: Get the real JAVA_HOME
  shell: readlink -f `which java` | sed "s/\/bin\/java$//"
  register: java_home
  always_run: true

- name: Ensure that the java home is set properly
  lineinfile: >
    dest=/home/vagrant/.bashrc
    line="export JAVA_HOME={{ java_home.stdout }}"

- name: installing git
  yum: name=git state=present

- name: ntp
  yum: name=ntp state=present
  tags: [ntp]

- name: start ntp server
  service: name=ntpd state=started enabled=yes
  tags: [ntp]
